import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight,CheckCircle2 } from "lucide-react";
import { getPage,getServices } from "@/lib/data";
import { CTASection,PageHero,SectionHeading } from "@/components/site/ui";
import { Stagger,StaggerItem } from "@/components/site/reveal";
import { notFound } from "next/navigation";
export const metadata:Metadata={title:"About Rack & Stack",description:"Rack & Stack plans and delivers storage systems around your space, loads and workflow."};
export default async function AboutPage(){const [page,services]=await Promise.all([getPage("about"),getServices()]);if(!page)notFound();return <main><PageHero eyebrow="About Rack & Stack" title={page.heroTitle||page.title} description={page.heroDescription} image={page.heroImage} breadcrumb={[{label:"About"}]}/><section className="py-24"><div className="container-shell grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Company profile" title="A Practical Partner for Your Storage Needs"/><div className="prose-copy text-lg">{page.content.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</div></div></section><section className="surface-grid bg-[#f4f4f1] py-24"><div className="container-shell"><SectionHeading eyebrow="What we do" title="Help From First Plan to Final Setup"/><Stagger className="mt-10 grid gap-px bg-zinc-300 md:grid-cols-2 lg:grid-cols-4">{services.slice(0,8).map((s,i)=><StaggerItem key={s.id} className="h-full"><Link href={`/services/${s.slug}`} className="group flex h-full flex-col bg-white p-6 hover:bg-zinc-950 hover:text-white"><span className="text-xs font-bold text-red-600">{String(i+1).padStart(2,"0")}</span><h3 className="mt-8 text-lg font-semibold">{s.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{s.shortDescription}</p><ArrowRight className="mt-6 text-red-600" size={16}/></Link></StaggerItem>)}</Stagger></div></section><section className="bg-zinc-950 py-24 text-white"><div className="container-shell grid gap-14 lg:grid-cols-2"><SectionHeading eyebrow="Our approach" title="Good Decisions Start With Good Information" description="We don't believe in one-size-fits-all. The right answer comes from understanding how you work." light/><Stagger className="grid gap-px bg-white/10 sm:grid-cols-2">{["What you store and its size","Your actual load weights","How you access and pick items","Building and equipment limits","Site and installation needs","Future changes to your operation"].map(item=><StaggerItem key={item} className="flex gap-3 bg-zinc-950 p-5 text-sm"><CheckCircle2 size={17} className="shrink-0 text-red-500"/>{item}</StaggerItem>)}</Stagger></div></section><CTASection title="Let’s Understand Your Needs Before Choosing a System."/></main>}
