import type { Metadata } from "next";
import { Clock,Mail,MapPin,MessageCircle,Phone } from "lucide-react";
import { getGallery,getGlobalFaqs,getSiteSettings } from "@/lib/data";
import { PageHero,SectionHeading } from "@/components/site/ui";
import { ContactForm } from "@/components/site/contact-form";
import { FAQ } from "@/components/site/faq";
import { phoneHref,whatsappHref } from "@/lib/utils";
import { notFound } from "next/navigation";
export const metadata:Metadata={title:"Contact",description:"Contact Rack & Stack Storage Systems about racking, shelving, mezzanine and custom storage requirements."};
export default async function ContactPage(){const [settings,faqs,gallery]=await Promise.all([getSiteSettings(),getGlobalFaqs(),getGallery()]);if(!settings)notFound();const contacts=[{label:"Call",value:`${settings.primaryPhone}${settings.secondaryPhone?` / ${settings.secondaryPhone}`:""}`,href:phoneHref(settings.primaryPhone),Icon:Phone},{label:"WhatsApp",value:settings.whatsapp,href:whatsappHref(settings.whatsapp),Icon:MessageCircle},{label:"Email",value:settings.email,href:`mailto:${settings.email}`,Icon:Mail},{label:"Working hours",value:settings.workingHours,Icon:Clock}];return <main><PageHero eyebrow="Contact" title="Tell Us What You Need" description="Share whatever space, stock and handling details you have. We'll take it from there." image={gallery[0]?.imageUrl} breadcrumb={[{label:"Contact"}]}/><section className="py-24"><div className="container-shell grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading eyebrow="Get in touch" title="Talk to Our Team."/><div className="mt-8 divide-y divide-zinc-200 border-y border-zinc-200">{contacts.map(({label,value,href,Icon})=>href?<a href={href} target={label==="WhatsApp"?"_blank":undefined} rel="noreferrer" key={label} className="flex items-center gap-4 py-5"><span className="grid h-10 w-10 place-items-center bg-zinc-100 text-red-600"><Icon size={18}/></span><span><small className="block text-[.62rem] font-bold uppercase tracking-widest text-zinc-400">{label}</small><strong className="mt-1 block text-sm">{value}</strong></span></a>:<div key={label} className="flex items-center gap-4 py-5"><span className="grid h-10 w-10 place-items-center bg-zinc-100 text-red-600"><Icon size={18}/></span><span><small className="block text-[.62rem] font-bold uppercase tracking-widest text-zinc-400">{label}</small><strong className="mt-1 block text-sm">{value}</strong></span></div>)}</div><div className="mt-8 flex gap-4 border border-zinc-200 p-5"><MapPin className="shrink-0 text-red-600" size={20}/><div><p className="text-xs font-bold uppercase tracking-widest text-zinc-400">Office &amp; works</p><address className="mt-2 text-sm not-italic leading-6 text-zinc-600">{settings.address}</address></div></div></div><div className="bg-[#f4f4f1] p-6 sm:p-10"><h2 className="text-2xl font-semibold">Send a Message</h2><p className="mt-2 text-sm text-zinc-500">For detailed storage requirements, please use the request a quote form.</p><div className="mt-8"><ContactForm/></div></div></div></section>{faqs.length>0&&<section id="faqs" className="bg-[#f4f4f1] py-24"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="FAQs" title="Answers Before You Call."/><FAQ items={faqs}/></div></section>}</main>}
