import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight,CheckCircle2 } from "lucide-react";
import { getIndustryBySlug } from "@/lib/data";
import { BenefitsList,CTASection,PageHero,ProductCard,SectionHeading } from "@/components/site/ui";
import { Stagger,StaggerItem } from "@/components/site/reveal";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=await getIndustryBySlug((await params).slug);return item?{title:item.metaTitle||`${item.name} Storage Solutions`,description:item.metaDescription||item.shortDescription}:{}}
export default async function IndustryPage({params}:{params:Promise<{slug:string}>}){const item=await getIndustryBySlug((await params).slug);if(!item)notFound();return <main><PageHero eyebrow="Industry solutions" title={`Storage for ${item.name}.`} description={item.shortDescription} image={item.heroImage} breadcrumb={[{label:"Industries",href:"/industries"},{label:item.name}]}/><section className="py-24"><div className="container-shell grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Your industry" title="We Understand Your Storage Challenges First."/><p className="text-xl leading-9 text-zinc-700">{item.description}</p></div></section><section className="surface-grid bg-[#f4f4f1] py-24"><div className="container-shell grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Common challenges" title="Enough Space and Easy Access, Together."/><Stagger className="mt-8 space-y-3">{(item.challenges||[]).map(c=><StaggerItem key={c} className="flex gap-3 bg-white p-4 text-sm"><CheckCircle2 size={17} className="text-red-600"/>{c}</StaggerItem>)}</Stagger></div><div><SectionHeading eyebrow="Potential benefits" title="What You Gain"/><div className="mt-8"><BenefitsList items={item.benefits||[]}/></div></div></div></section><section className="py-24"><div className="container-shell"><SectionHeading eyebrow="Recommended systems" title={`Systems That Work for ${item.name}.`} description="The final choice depends on your stock, loads, equipment and building."/><Stagger className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{item.products.map((p,i)=><StaggerItem key={p.id} className="h-full"><ProductCard product={p} index={i}/></StaggerItem>)}</Stagger></div></section><section className="bg-zinc-950 py-24 text-white"><div className="container-shell"><SectionHeading eyebrow="Services" title="Expert Help Before and During Your Project." light/><Stagger className="mt-10 grid gap-px bg-white/10 md:grid-cols-3">{item.services.map(s=><StaggerItem key={s.id} className="h-full"><Link href={`/services/${s.slug}`} className="group flex h-full flex-col bg-zinc-950 p-7 hover:bg-zinc-900"><h3 className="text-xl font-semibold">{s.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{s.shortDescription}</p><ArrowRight className="mt-7 text-red-500 transition-transform group-hover:translate-x-1" size={17}/></Link></StaggerItem>)}</Stagger></div></section><CTASection title={`Let's Discuss Your ${item.name} Storage Needs.`}/></main>}
