import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { getIndustries } from "@/lib/data";
import { PageHero,SectionHeading,CTASection } from "@/components/site/ui";
import { Stagger,StaggerItem } from "@/components/site/reveal";
import { SmartImage } from "@/components/site/smart-image";
export const metadata:Metadata={title:"Industries",description:"Storage systems and warehouse layouts for manufacturing, logistics, retail, e-commerce, offices and more."};
export default async function IndustriesPage(){const items=await getIndustries();return <main><PageHero eyebrow="Industries" title="Storage for Every Industry" description="Every business stores things differently. We plan around your stock, handling and space." image={items[0]?.heroImage} breadcrumb={[{label:"Industries"}]}/><section className="py-24"><div className="container-shell"><SectionHeading eyebrow="Who we serve" title="Find Your Industry"/><Stagger className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map((item,i)=><StaggerItem key={item.id} className="h-full"><Link href={`/industries/${item.slug}`} className="card-lift group relative flex h-full min-h-[390px] overflow-hidden bg-zinc-950 text-white"><SmartImage src={item.heroImage||""} alt={`${item.name} storage`} fill className="object-cover opacity-50 transition duration-700 group-hover:scale-105" sizes="33vw"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7"><span className="text-xs font-bold text-red-400">{String(i+1).padStart(2,"0")}</span><h2 className="card-title mt-3">{item.name}</h2><p className="mt-3 text-sm leading-6 text-zinc-300">{item.shortDescription}</p><ArrowRight size={17} className="mt-6 transition-transform group-hover:translate-x-1"/></div></Link></StaggerItem>)}</Stagger></div></section><CTASection title="Let's Plan Storage Around Your Business"/></main>}
