import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight,MapPin } from "lucide-react";
import { getGallery,getProjects } from "@/lib/data";
import { CTASection,EmptyState,PageHero,SectionHeading } from "@/components/site/ui";
import { Stagger,StaggerItem } from "@/components/site/reveal";
import { SmartImage } from "@/components/site/smart-image";
export const metadata:Metadata={title:"Storage Projects",description:"Explore our industrial storage, warehouse racking and space optimization projects."};
export default async function ProjectsPage(){const [items,gallery]=await Promise.all([getProjects(),getGallery()]);return <main><PageHero eyebrow="Projects" title="Our Projects" description="See real projects — the requirement, the solution and how we delivered it." image={items[0]?.coverImage||gallery[0]?.imageUrl} breadcrumb={[{label:"Projects"}]}/><section className="py-24"><div className="container-shell"><SectionHeading eyebrow="Selected work" title="A Look at Our Recent Work" description="Only approved projects are shown here."/>{items.length===0?<div className="mt-10"><EmptyState title="Projects Are Coming Soon" description="New case studies will appear here once approved. Talk to our team to hear about similar work."/></div>:<Stagger className="mt-12 grid gap-5 md:grid-cols-2">{items.map(item=><StaggerItem key={item.id} className="h-full min-w-0"><Link href={`/projects/${item.slug}`} className="card-lift group flex h-full flex-col overflow-hidden border border-zinc-200"><div className="relative h-80"><SmartImage src={item.coverImage||""} alt={item.title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 767px) 100vw, 50vw"/></div><div className="p-7"><p className="text-[.62rem] font-bold uppercase tracking-widest text-red-600">{item.industry||"Storage project"}</p><h2 className="card-title mt-3">{item.title}</h2>{item.location&&<p className="mt-3 flex items-center gap-2 text-xs text-zinc-500"><MapPin size={14}/>{item.location}</p>}<p className="mt-4 line-clamp-2 text-sm leading-6 text-zinc-600">{item.description}</p><span className="mt-6 flex items-center gap-2 text-xs font-bold">View Case Study <ArrowRight size={15}/></span></div></Link></StaggerItem>)}</Stagger>}</div></section><CTASection title="Need a Storage Plan for Your Project?"/></main>}
