"use client";
import Link from "next/link";
import { ChevronDown, Download, Menu, MessageCircle, Phone, Search, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Logo } from "./logo";
import type { products } from "@/db/schema";
type Product = typeof products.$inferSelect;
export function Header({ products, phone, whatsapp }: { products: Product[]; phone: string; whatsapp: string }) {
  const [mobile,setMobile]=useState(false); const [mega,setMega]=useState(false); const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const fn=()=>setScrolled(window.scrollY>20);fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);
  useEffect(()=>{document.body.style.overflow=mobile?"hidden":"";return()=>{document.body.style.overflow=""}},[mobile]);
  const groups=[{title:"Industrial Racking",items:products.filter(p=>p.category==="Industrial Racking")},{title:"Space Optimization",items:products.filter(p=>p.category==="Space Optimization")},{title:"Workplace Storage",items:products.filter(p=>p.category==="Workplace Storage")}];
  return <header className={`sticky top-0 z-50 border-b bg-white/95 backdrop-blur-xl transition-shadow ${scrolled?"border-zinc-200 shadow-[0_8px_30px_rgba(0,0,0,.06)]":"border-zinc-200"}`}>
    <div className="hidden bg-zinc-950 py-2 text-[.68rem] font-medium text-zinc-300 lg:block"><div className="container-shell flex justify-between"><span>Industrial storage systems planned around your operation</span><div className="flex gap-6"><a href={`tel:${phone.replace(/\s/g,"")}`} className="hover:text-white">{phone}</a><a href={`https://wa.me/${whatsapp.replace(/\D/g,"")}`} className="hover:text-white">WhatsApp</a></div></div></div>
    <div className="container-shell flex h-[72px] items-center justify-between"><Logo/><nav aria-label="Main navigation" className="hidden h-full items-center gap-7 lg:flex">
      <div className="h-full" onMouseEnter={()=>setMega(true)} onMouseLeave={()=>setMega(false)}><button className="flex h-full items-center gap-1 text-[.78rem] font-bold text-zinc-700 hover:text-red-700" onClick={()=>setMega(!mega)} aria-expanded={mega}>Products <ChevronDown size={14}/></button>
        {mega&&<div className="absolute left-0 right-0 top-full border-y border-zinc-200 bg-white shadow-2xl"><div className="container-shell grid grid-cols-[.7fr_1fr_1fr_1fr] gap-10 py-9"><div className="bg-zinc-950 p-6 text-white"><p className="text-[.65rem] font-bold uppercase tracking-[.18em] text-red-400">Product systems</p><h2 className="mt-3 text-2xl font-semibold leading-tight">Engineered around load, space and access.</h2><Link onClick={()=>setMega(false)} href="/products" className="mt-8 inline-flex border-b border-red-500 pb-1 text-xs font-bold">View all products →</Link></div>{groups.map(group=><div key={group.title}><p className="mb-4 text-[.67rem] font-extrabold uppercase tracking-[.14em] text-zinc-400">{group.title}</p><div className="space-y-1">{group.items.map(item=><Link key={item.id} onClick={()=>setMega(false)} href={`/products/${item.slug}`} className="block border-l-2 border-transparent px-3 py-2 hover:border-red-600 hover:bg-zinc-50"><span className="block text-sm font-semibold">{item.name}</span><span className="mt-1 line-clamp-1 text-[.68rem] text-zinc-500">{item.shortDescription}</span></Link>)}</div></div>)}</div></div>}
      </div>
      {[['Services','/services'],['Industries','/industries'],['Projects','/projects'],['About','/about'],['Resources','/blog']].map(([label,href])=><Link key={href} href={href} className="text-[.78rem] font-bold text-zinc-700 hover:text-red-700">{label}</Link>)}
    </nav><div className="flex items-center gap-2"><Link href="/search" aria-label="Search website" className="hidden h-10 w-10 place-items-center text-zinc-700 hover:bg-zinc-100 sm:grid"><Search size={18}/></Link><a href={`https://wa.me/${whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" aria-label="WhatsApp" className="hidden h-10 w-10 place-items-center text-zinc-700 hover:bg-zinc-100 md:grid"><MessageCircle size={18}/></a><Link href="/catalog" className="hidden items-center gap-2 px-2 text-[.72rem] font-bold text-zinc-700 hover:text-red-700 xl:flex"><Download size={15}/>Catalog</Link><Link href="/request-a-quote" className="btn-primary hidden lg:inline-flex">Request a Quote</Link><Link href="/request-a-quote" className="inline-flex min-h-9 items-center bg-red-600 px-3 text-[.68rem] font-bold text-white lg:hidden">Quote</Link><button className="grid h-11 w-11 place-items-center lg:hidden" onClick={()=>setMobile(true)} aria-label="Open menu"><Menu/></button></div></div>
    {mobile&&<div className="fixed inset-0 z-[70] min-h-screen overflow-y-auto bg-zinc-950 text-white lg:hidden"><div className="flex h-[72px] items-center justify-between border-b border-white/10 px-5"><Logo light/><button onClick={()=>setMobile(false)} aria-label="Close menu"><X/></button></div><nav className="px-5 py-8"><p className="mb-3 text-[.64rem] font-bold uppercase tracking-[.18em] text-zinc-500">Solutions</p>{products.map(item=><Link onClick={()=>setMobile(false)} key={item.id} href={`/products/${item.slug}`} className="block border-b border-white/10 py-3 text-base">{item.name}</Link>)}<div className="mt-8 grid grid-cols-2 gap-px bg-white/10">{[['Services','/services'],['Industries','/industries'],['Projects','/projects'],['About','/about'],['Resources','/blog'],['Contact','/contact']].map(([label,href])=><Link onClick={()=>setMobile(false)} key={href} href={href} className="bg-zinc-950 p-4 text-sm font-semibold">{label}</Link>)}</div><Link onClick={()=>setMobile(false)} href="/catalog" className="btn-light mt-8 w-full"><Download size={16}/>Download Catalog</Link><Link onClick={()=>setMobile(false)} href="/request-a-quote" className="btn-primary mt-3 w-full">Request a Quote</Link><div className="mt-4 flex gap-2"><a className="btn-light flex-1" href={`tel:${phone.replace(/\s/g,"")}`}><Phone size={16}/> Call</a><Link className="btn-light flex-1" href="/search"><Search size={16}/> Search</Link></div></nav></div>}
  </header>;
}
