import Link from "next/link";
import { ArrowRight, Check, ChevronRight, Download } from "lucide-react";
import { SmartImage } from "./smart-image";
import type { products,services } from "@/db/schema";
export function SectionHeading({eyebrow,title,description,light=false,align="left"}:{eyebrow?:string;title:string;description?:string|null;light?:boolean;align?:"left"|"center"}){return <div className={`${align==="center"?"mx-auto max-w-3xl text-center":"max-w-3xl"}`}>{eyebrow?<p className={`eyebrow ${align==="center"?"justify-center before:hidden":""}`}>{eyebrow}</p>:null}<h2 className={`heading-lg mt-5 text-balance ${light?"text-white":"text-zinc-950"}`}>{title}</h2>{description&&<p className={`mt-5 max-w-2xl text-base leading-7 ${align==="center"?"mx-auto":""} ${light?"text-zinc-400":"text-zinc-600"}`}>{description}</p>}</div>}
export function Breadcrumb({items}:{items:Array<{label:string;href?:string}>}){return <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-[.68rem] font-bold uppercase tracking-[.1em] text-zinc-500"><Link href="/">Home</Link>{items.map((item,i)=><span className="flex items-center gap-2" key={`${item.label}-${i}`}><ChevronRight size={12}/>{item.href?<Link href={item.href}>{item.label}</Link>:<span className="text-zinc-300">{item.label}</span>}</span>)}</nav>}
export function PageHero({eyebrow,title,description,image,breadcrumb}:{eyebrow:string;title:string;description?:string|null;image?:string|null;breadcrumb?:Array<{label:string;href?:string}>}){return <section className="relative isolate min-h-[460px] overflow-hidden bg-zinc-950 text-white"><div className="absolute inset-0 -z-20">{image&&<SmartImage src={image} alt="" fill priority className="object-cover opacity-40" sizes="100vw"/>}</div><div className="absolute inset-0 -z-10 bg-gradient-to-r from-zinc-950 via-zinc-950/85 to-zinc-950/25"/><div className="container-shell flex min-h-[460px] flex-col justify-end py-16"><div className="max-w-4xl">{breadcrumb&&<Breadcrumb items={breadcrumb}/>}<p className="eyebrow mt-8 text-red-400">{eyebrow}</p><h1 className="heading-lg mt-5 text-balance">{title}</h1>{description&&<p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-300">{description}</p>}</div></div></section>}
type Product=typeof products.$inferSelect; type Service=typeof services.$inferSelect;
export function ProductCard({product,index=0}:{product:Product;index?:number}){return <Link href={`/products/${product.slug}`} className="card-lift group flex min-h-[480px] flex-col overflow-hidden border border-zinc-200 bg-white"><div className="relative h-64 overflow-hidden bg-zinc-200">{product.thumbnail||product.heroImage?<SmartImage src={product.thumbnail||product.heroImage||""} alt={product.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/>:null}<span className="absolute left-4 top-4 bg-zinc-950 px-2 py-1 text-[.6rem] font-bold text-white">{String(index+1).padStart(2,"0")}</span></div><div className="flex grow flex-col p-6"><p className="text-[.63rem] font-bold uppercase tracking-[.14em] text-red-600">{product.category}</p><h3 className="mt-3 text-xl font-semibold tracking-tight">{product.name}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-zinc-600">{product.shortDescription}</p><span className="mt-auto flex items-center gap-2 pt-6 text-xs font-bold">Explore system <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></span></div></Link>}
export function ServiceCard({service,index=0}:{service:Service;index?:number}){return <Link href={`/services/${service.slug}`} className="group border-t border-zinc-300 py-7 transition-colors hover:bg-zinc-950 hover:px-6 hover:text-white"><div className="flex items-start gap-5"><span className="mt-1 text-xs font-bold text-red-600">{String(index+1).padStart(2,"0")}</span><div className="grow"><h3 className="text-xl font-semibold tracking-tight">{service.name}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-zinc-600 group-hover:text-zinc-400">{service.shortDescription}</p></div><ArrowRight className="mt-1 shrink-0 transition-transform group-hover:translate-x-1" size={19}/></div></Link>}
export function CTASection({title,description="Share your space, inventory and handling requirements. Our team will help identify the right next step.",product}:{title:string;description?:string;product?:string}){return <section className="dark-grid bg-zinc-950 py-20 text-white"><div className="container-shell flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><div className="max-w-3xl"><p className="eyebrow text-red-400">Start a conversation</p><h2 className="heading-lg mt-5 text-balance">{title}</h2><p className="mt-5 max-w-2xl text-zinc-400">{description}</p></div><div className="flex shrink-0 flex-wrap gap-3"><Link href={product?`/request-a-quote?product=${encodeURIComponent(product)}`:"/request-a-quote"} className="btn-primary">Request a Quote <ArrowRight size={17}/></Link><Link href="/catalog" className="btn-light"><Download size={16}/>Catalog</Link></div></div></section>}
export function BenefitsList({items}:{items:string[]}){return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className="flex items-start gap-3 border border-zinc-200 p-4 text-sm"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center bg-red-600 text-white"><Check size={12}/></span>{item}</li>)}</ul>}
export function EmptyState({title,description}:{title:string;description:string}){return <div className="border border-dashed border-zinc-300 bg-zinc-50 p-12 text-center"><h2 className="text-xl font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-zinc-500">{description}</p></div>}
export function JsonLd({data}:{data:Record<string,unknown>}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,"\\u003c")}}/>}
