import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Calendar,MapPin } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { getProjectBySlug } from "@/lib/data";
import { CTASection,PageHero,ProductCard,SectionHeading } from "@/components/site/ui";
import { SmartImage } from "@/components/site/smart-image";
import { EventTracker } from "@/components/site/event-tracker";
import { Stagger,StaggerItem } from "@/components/site/reveal";
import { formatDate } from "@/lib/utils";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=await getProjectBySlug((await params).slug);return item?{title:item.metaTitle||item.title,description:item.metaDescription||item.description,alternates:{canonical:item.canonicalUrl||`/projects/${item.slug}`}}:{}}
export default async function ProjectPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{preview?:string}>}){const [{slug},{preview}]=await Promise.all([params,searchParams]);const item=await getProjectBySlug(slug,preview==="1"&&Boolean(await getCurrentUser()));if(!item)notFound();return <main><EventTracker eventName="project_view" entityType="project" entityId={item.id}/><PageHero eyebrow={item.industry||"Project"} title={item.title} description={item.description} image={item.coverImage} breadcrumb={[{label:"Projects",href:"/projects"},{label:item.title}]}/><section className="border-b border-zinc-200"><div className="container-shell grid sm:grid-cols-3">{[["Client",item.clientName||"Confidential"],["Location",item.location||"Not published"],["Project date",formatDate(item.projectDate)]].map(([label,value],i)=><div className={`py-7 ${i?"sm:border-l sm:pl-7":""}`} key={label}><p className="text-[.62rem] font-bold uppercase tracking-widest text-zinc-400">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>)}</div></section><section className="py-24"><div className="container-shell space-y-20">{[["The challenge",item.challenge],["The solution",item.solutionDescription],["Execution",item.execution],["Result",item.result]].filter(([,body])=>body).map(([title,body],i)=><div className="grid gap-10 lg:grid-cols-[.55fr_1.45fr]" key={title}><p className="eyebrow">0{i+1} / {title}</p><p className="text-xl leading-9 text-zinc-700">{body}</p></div>)}</div></section>{item.images.length>0&&<section className="bg-[#f4f4f1] py-24"><div className="container-shell"><SectionHeading eyebrow="Project gallery" title="Implementation in context."/><Stagger className="mt-10 grid gap-4 md:grid-cols-2">{item.images.map(image=><StaggerItem key={image.id} className="h-full"><div className="relative h-96"><SmartImage src={image.imageUrl} alt={image.altText} fill className="object-cover" sizes="50vw"/></div></StaggerItem>)}</Stagger></div></section>}{item.products.length>0&&<section className="py-24"><div className="container-shell"><SectionHeading eyebrow="Systems used" title="Explore the products connected to this project."/><Stagger className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{item.products.map((product,index)=><StaggerItem key={product.id} className="h-full"><ProductCard product={product} index={index}/></StaggerItem>)}</Stagger></div></section>}<CTASection title="Discuss a project with similar constraints."/></main>}
