import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { getBlogPosts,getGallery } from "@/lib/data";
import { EmptyState,PageHero,SectionHeading } from "@/components/site/ui";
import { SmartImage } from "@/components/site/smart-image";
import { formatDate } from "@/lib/utils";
export const metadata:Metadata={title:"Warehouse Storage Resources",description:"Practical guides about storage systems, warehouse optimization, safety, space planning and material handling."};
export default async function BlogPage(){const [rows,gallery]=await Promise.all([getBlogPosts(),getGallery()]);return <main><PageHero eyebrow="Resources" title="Better inputs lead to better storage decisions." description="Practical notes for teams planning warehouses, reviewing capacity or comparing storage systems." image={rows[0]?.post.featuredImage||gallery[0]?.imageUrl} breadcrumb={[{label:"Resources"}]}/><section className="py-24"><div className="container-shell"><SectionHeading eyebrow="Latest thinking" title="Guides for planning teams and operators."/>{rows.length===0?<div className="mt-10"><EmptyState title="No resources published yet." description="Published CMS articles will appear here."/></div>:<div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{rows.map(({post,category})=><Link href={`/blog/${post.slug}`} key={post.id} className="card-lift group border border-zinc-200 bg-white"><div className="relative h-60 overflow-hidden"><SmartImage src={post.featuredImage||""} alt={post.title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="33vw"/></div><div className="p-6"><p className="text-[.62rem] font-bold uppercase tracking-widest text-red-600">{category?.name||"Resource"} · {formatDate(post.publishedAt)}</p><h2 className="mt-3 text-xl font-semibold leading-tight">{post.title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{post.excerpt}</p><span className="mt-6 flex items-center gap-2 text-xs font-bold">Read guide <ArrowRight size={15}/></span></div></Link>)}</div>}</div></section></main>}
